apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zhu6g944x-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zhu6g944x-nodejs 
  name: zhu6g944x-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: zhu6g944x-nodejs 
